name: Logs for Netlify

on:
  # you can deploy to netlify based on branches or pull requests
  pull_request:
    branches:
    - master
  push:
    branches:
      - master
      
jobs:
  logs4netlify:
    name: Logs for Netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Logs
      uses: bdougie/loglify@master
