name: Performance Testing
on:
  deployment_status:
  workflow_dispatch:
    inputs:
      domain:
        required: true
        default: 'tiarebalbi.com'
        description: Domain (with https)
      vus:
        required: true
        default: 10
        description: Number of virtual users
      minTime:
        required: true
        default: '1m'
        description: Min time
      maxTime:
        required: true
        default: '5m'
        description: Max time
jobs:
  k6_local_perf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run local k6 test (${{ github.event_name }})
        uses: k6io/action@v0.1
        with:
          filename: perf/k6-tiarebalbi.js
          flags: >-
            -e TARGET_VUS=${{ github.event.inputs.vus }} 
            -e INPUT_DOMAIN=${{ github.event.inputs.domain }} 
            -e MIN_TIME=${{ github.event.inputs.minTime }} 
            -e MAX_TIME=${{ github.event.inputs.maxTime }} 
            -e DEPLOYMENT_DOMAIN=${{ github.event.deployment_status.target_url }} 
  google_insights_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'deployment_status'}}
    steps:
      - name: Running Page Speed Insights (Mobile)
        uses: jakepartusch/psi-action@v1.1
        id: psi-mob
        with:
          url: '${{ github.event.deployment_status.target_url }}/'
          threshold: 75
          strategy: mobile
      - name: Running Page Speed Insights (Desktop)
        uses: jakepartusch/psi-action@v1.1
        id: psi-des
        with:
          url: '${{ github.event.deployment_status.target_url }}/'
          threshold: 90
          strategy: desktop
          
  google_insights_input:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch'}}
    steps:
      - name: Running Page Speed Insights (Mobile)
        uses: jakepartusch/psi-action@v1.1
        id: psi-mob
        with:
          url: '${{ github.event.inputs.domain }}/'
          threshold: 75
          strategy: mobile
      - name: Running Page Speed Insights (Desktop)
        uses: jakepartusch/psi-action@v1.1
        id: psi-des
        with:
          url: '${{ github.event.inputs.domain }}/'
          threshold: 90
          strategy: desktop
