name: Performance Testing
on:
  deployment_status:
  workflow_dispatch:
    inputs:
      domain:
        required: true
        default: 'tiarebalbi.com'
        description: Domain (with https)
      vus:
        required: true
        default: 10
        description: Number of virtual users
      minTime:
        required: true
        default: '1m'
        description: Min time
      maxTime:
        required: true
        default: '5m'
        description: Max time
jobs:
  k6_local_perf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1
      - name: Run local k6 test (${{ github.event_name }})
        uses: k6io/action@v0.2.0
        with:
          filename: perf/k6-tiarebalbi.js
          flags: >-
            -e TARGET_VUS=${{ github.event.inputs.vus }} 
            -e INPUT_DOMAIN=${{ github.event.inputs.domain }} 
            -e MIN_TIME=${{ github.event.inputs.minTime }} 
            -e MAX_TIME=${{ github.event.inputs.maxTime }} 
            -e DEPLOYMENT_DOMAIN=${{ github.event.deployment_status.target_url }} 
