name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 3 * * 2

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn
      - run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1
        id: psi
        with:
          url: "https://tiarebalbi.com"
          threshold: 70
          strategy: mobile
