name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * 1-5

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{secrets.GH_PAT}}
        with:
          BUILD_DIR: "/home/runner/work/vigilant-react-typescript/vigilant-react-typescript/docs"
