name: CI / Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3.6.0
        with:
          version: ${{ matrix.node_version }}
      - name: Cache multiple paths
        uses: actions/cache@v3.3.1
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: npm install and test
        run: |
          yarn
          yarn build
